spring:
 application:
   name: Config-prod
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8671/eureka
    instance:
      prefer-ip-address: true

